USE master;
ALTER DATABASE SUPREMO_Gruger_Geradores SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
ALTER DATABASE SUPREMO_Gruger_Geradores MODIFY NAME = [SUPREMO_Gruger_Geradores_Copia];
ALTER DATABASE SUPREMO_Gruger_Geradores_Copia SET MULTI_USER;