--drop table cliente_export;
create table transportadora_export as
select x."CPF/CNPJ"
     , x."INSCRICAO_ESTADUAL"
     , x."RAZAOSOCIAL"
     , x."NOMEFANTASIA"
     , x."CEP"
     , x."LOGRADOURO"
     , x."NUMERO"
     , x."COMPLEMENTO"
     , x."MUNICIPIO"
     , x."BAIRRO"
     , x."UF"
     , coalesce(x."IBGE",4115200)  
     , x."CLIENTE"
     , x."FORNECEDOR" 
     , x."TELEFONE"
    , x."TELEFONE_ADICIONAL"
    , x."TELEFONE_EXTRA"
    , x."EMAIL"
    , x."SITE"
    , x."CODIGO"
    , x."CNPJ_VALIDO"   
from (
select c.cpfcnpj as "CPF/CNPJ"
    , c.rginscest as "INSCRICAO_ESTADUAL"
    , c.razao as "RAZAOSOCIAL"
    , c.fantasia as "NOMEFANTASIA"
    , c.cep as "CEP"
    , c.endereco as "LOGRADOURO"
    , c.numero as "NUMERO"
    , c.complemento as "COMPLEMENTO"
    , c.cidade as "MUNICIPIO"
    , c.bairro as "BAIRRO"
    , c.uf as "UF"
    , retornaIBGE(c.cidade,c.uf) as "IBGE"
    , 0 as "CLIENTE"
    , 1 as "FORNECEDOR" 
    , ajusta_tel(c.fone) as "TELEFONE"
    , ajusta_tel(c.celular) as "TELEFONE_ADICIONAL"
    , ajusta_tel(c.fax) as "TELEFONE_EXTRA"
    , c.email as "EMAIL"
    , '' as "SITE"
    , CAST(c.codtrans as int) as "CODIGO"
    , validaCnpjCpf(c.cpfcnpj) as "CNPJ_VALIDO"
from transpor c
where c.ativada <> 0 
  AND c.codtrans > 0) as x
