drop table fornecedor_export;
create table fornecedor_export as
select x."CPF/CNPJ"
     , x."INSCRICAO_ESTADUAL"
     , x."RAZAOSOCIAL"
     , x."NOMEFANTASIA"
     , x."CEP"
     , x."LOGRADOURO"
     , x."NUMERO"
     , x."COMPLEMENTO"
     , x."MUNICIPIO"
     , x."BAIRRO"
     , x."UF"
     , coalesce(x."IBGE",4115200)  
     , x."CLIENTE"
     , x."FORNECEDOR" 
     , x."TELEFONE"
    , x."TELEFONE_ADICIONAL"
    , x."TELEFONE_EXTRA"
    , x."EMAIL"
    , x."SITE"
    , x."CODIGO"
    , x."CNPJ_VALIDO"   
from (
select c.cnpj as "CPF/CNPJ"
    , c.inscest as "INSCRICAO_ESTADUAL"
    , c.razao as "RAZAOSOCIAL"
    , c.fantasia as "NOMEFANTASIA"
    , c.cep as "CEP"
    , c.endereco as "LOGRADOURO"
    , c.numero as "NUMERO"
    , c.complemento as "COMPLEMENTO"
    , c.cidade as "MUNICIPIO"
    , c.bairro as "BAIRRO"
    , c.uf as "UF"
    , (SELECT codibge FROM dblink('host=127.0.0.1 user=postgres password=161851 dbname=cep2018',
               'select codcidade,nome,uf,codibge from cep_cidade')
     AS t1(codcidade int,nome text,uf text,codibge int) where nome=unaccent(c.cidade) and uf=upper(c.uf) limit 1)as "IBGE" as "IBGE"
    , 0 as "CLIENTE"
    , 1 as "FORNECEDOR" 
    , ajusta_tel(c.fone) as "TELEFONE"
    , ajusta_tel(c.celular) as "TELEFONE_ADICIONAL"
    , ajusta_tel(c.fax) as "TELEFONE_EXTRA"
    , c.email as "EMAIL"
    , c.site as "SITE"
    , CAST(c.codfor as int) as "CODIGO"
    , validaCnpjCpf(c.cnpj) as "CNPJ_VALIDO"
from fornec c
where c.bloqueado <> 0 
  AND c.codfor > 0) as x
